/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RsvpRouteImport } from './routes/rsvp'
import { Route as InvitationRouteImport } from './routes/invitation'
import { Route as FamilyRouteImport } from './routes/family'
import { Route as CelebrationRouteImport } from './routes/celebration'
import { Route as IndexRouteImport } from './routes/index'

const RsvpRoute = RsvpRouteImport.update({
  id: '/rsvp',
  path: '/rsvp',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationRoute = InvitationRouteImport.update({
  id: '/invitation',
  path: '/invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyRoute = FamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => rootRouteImport,
} as any)
const CelebrationRoute = CelebrationRouteImport.update({
  id: '/celebration',
  path: '/celebration',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/celebration': typeof CelebrationRoute
  '/family': typeof FamilyRoute
  '/invitation': typeof InvitationRoute
  '/rsvp': typeof RsvpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/celebration': typeof CelebrationRoute
  '/family': typeof FamilyRoute
  '/invitation': typeof InvitationRoute
  '/rsvp': typeof RsvpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/celebration': typeof CelebrationRoute
  '/family': typeof FamilyRoute
  '/invitation': typeof InvitationRoute
  '/rsvp': typeof RsvpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/celebration' | '/family' | '/invitation' | '/rsvp'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/celebration' | '/family' | '/invitation' | '/rsvp'
  id: '__root__' | '/' | '/celebration' | '/family' | '/invitation' | '/rsvp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CelebrationRoute: typeof CelebrationRoute
  FamilyRoute: typeof FamilyRoute
  InvitationRoute: typeof InvitationRoute
  RsvpRoute: typeof RsvpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rsvp': {
      id: '/rsvp'
      path: '/rsvp'
      fullPath: '/rsvp'
      preLoaderRoute: typeof RsvpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitation': {
      id: '/invitation'
      path: '/invitation'
      fullPath: '/invitation'
      preLoaderRoute: typeof InvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family': {
      id: '/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof FamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/celebration': {
      id: '/celebration'
      path: '/celebration'
      fullPath: '/celebration'
      preLoaderRoute: typeof CelebrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CelebrationRoute: CelebrationRoute,
  FamilyRoute: FamilyRoute,
  InvitationRoute: InvitationRoute,
  RsvpRoute: RsvpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
